spring:
  messages:
    basename: i18n/messages
    encoding: UTF-8
  datasource:
    url: "jdbc:log4jdbc:mysql://127.0.0.1:3306/minitest?useSSL=false&autoReconnect=true&autoReconnection=true&useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&serverTimezone=Asia/Seoul"
    username: "root"
    password: "1q2w3e4r%%"
    driver-class-name: net.sf.log4jdbc.sql.jdbcapi.DriverSpy
    tomcat:
      max-active: 50
      max-idle: 50
      min-idle: 10
      max-wait: -1
      initial-size: 10
      test-on-borrow: true
      test-while-idle: true
      validation-query: 'select 1'
      time-between-eviction-runs-millis: 3000
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        physical_naming_strategy: org.springframework.boot.orm.jpa.hibernate.SpringPhysicalNamingStrategy
        enable_lazy_load_no_trans: true
  mvc:
    custom-uri-logging-filter:
      enabled: true
      level: info

social:
  client:
    kakao:
      rest-api-key: "e094e49e35c61a9da896785b6fee020a"
      secret-key: "EVUqAgvDALmABayw2DZo2jL0awEhVUH7"
      redirect-uri: "http://localhost:8080/kakao-login"
      grant_type: "authorization_code"
    naver:
      rest-api-key: "e094e49e35c61a9da896785b6fee020a"
      secret-key: "DEn_pJGqup"
      redirect-uri: "http://localhost:8080/naver-login"
      grant_type: "authorization_code"
    google:
      rest-api-key: "e094e49e35c61a9da896785b6fee020a"
      secret-key: "DEn_pJGqup"
      redirect-uri: "http://localhost:8080/google-login"
      grant_type: "authorization_code"
logging:
  level:
    org:
      hibernate:
        type:
          descriptor:
            sql: trace