jwt:
  secretKey: showmethemoney12345operationcwal67890blacksheepwall12345foodforthought67890
  access:
    #expiration: 3600000     # 1시간(60분) (1000L(ms -> s) * 60L(s -> m) * 60L(m -> h))
    expiration: 86400000     # 24시간(임시)
    header: Authorization
  refresh:
    expiration: 1209600000  # (1000L(ms -> s) * 60L(s -> m) * 60L(m -> h) * 24L(h -> 하루) * 14(2주))
    header: Authorization-refresh