spring:
  messages:
    basename: i18n/messages
    encoding: UTF-8
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        physical_naming_strategy: org.springframework.boot.orm.jpa.hibernate.SpringPhysicalNamingStrategy
        enable_lazy_load_no_trans: true
hyphen:
  user_id: cgt2022
  hkey: b461bceea477f528
jusogov:
  confirm-key:
    road_addr: devU01TX0FVVEgyMDI0MDQwMjIzMzA0OTExNDY1NTY=
    road_addr_detail : devU01TX0FVVEgyMDI0MDQwMjIzMzI1NzExNDY1NTc=
vworld:
  key: E3422A28-9B67-3BCF-912F-5B7BBE6C8318
logging:
  level:
    org:
      hibernate:
        type:
          descriptor:
            sql: trace