spring:
  messages:
    basename: i18n/messages
    encoding: UTF-8
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        physical_naming_strategy: org.springframework.boot.orm.jpa.hibernate.SpringPhysicalNamingStrategy
        enable_lazy_load_no_trans: true
hyphen:
  user_id: cgt2022
  hkey: b461bceea477f528
jusogov:
  confirm-key: devU01TX0FVVEgyMDI0MDEwMTAzNDMwOTExNDM5MzU=
logging:
  level:
    org:
      hibernate:
        type:
          descriptor:
            sql: trace