spring:
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: 123
            client-secret: 345
            redirect-uri: http://localhost:8080/google-login
            authorization-grant-type: authorization_code
            scope: profile, email
          naver:
            client-id: 123
            client-secret: DEn_pJGqup
            redirect-uri: http://localhost:8080/naver-login
            authorization-grant-type: authorization_code
            scope: name, email, profile_image
            client-name: Naver
          kakao:
            client-id: e094e49e35c61a9da896785b6fee020a
            client-secret: EVUqAgvDALmABayw2DZo2jL0awEhVUH7
            redirect-uri: http://localhost:8080/kakao-login
            client-authentication-method: POST
            authorization-grant-type: authorization_code
            scope:
            client-name: Kakao
        provider:
          naver:
            authorization_uri: https://nid.naver.com/oauth2.0/authorize
            token_uri: https://nid.naver.com/oauth2.0/token
            user-info-uri: https://openapi.naver.com/v1/nid/me
            user_name_attribute: response
          kakao:
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            token-uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user-name-attribute: id