social:
  client:
    kakao:
      rest-api-key: e094e49e35c61a9da896785b6fee020a
      secret-key: EVUqAgvDALmABayw2DZo2jL0awEhVUH7
      redirect-uri: http://localhost:8080/kakao-login
      grant_type: authorization_code

    naver:
      rest-api-key:
      secret-key: DEn_pJGqup
      redirect-uri: http://localhost:8080/naver-login
      grant_type: authorization_code

    google:
      rest-api-key:
      secret-key:
      redirect-uri: http://localhost:8080/google-login
      grant_type: authorization_code

logging:
  level:
    org:
      hibernate:
        type:
          descriptor:
            sql: trace
